---

- name: Ensure templates directory for createamneziassh role exists on control node
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "{{ playbook_dir }}/roles/createamneziassh/templates"
    state: directory
    mode: "0700"

- name: Generate SSH keypair for amnesia on control node
  delegate_to: localhost
  run_once: true
  ansible.builtin.openssh_keypair:
    path: "{{ playbook_dir }}/roles/createamneziassh/templates/amnesia_id_rsa"
    size: 4096
    type: rsa
    state: present

- name: Create Amnesia user
  ansible.builtin.user:
    name: amnesia
    shell: /bin/bash
    group: sudo
    password: "*"

- name: Create sshkey dir for amnesia
  ansible.builtin.file:
    path: /home/amnesia/.ssh
    state: directory
    owner: amnesia
    mode: 0700

- name: Install generated ssh public key for amnesia
  ansible.builtin.authorized_key:
    user: amnesia
    key: "{{ lookup('file', playbook_dir + '/roles/createamneziassh/templates/amnesia_id_rsa.pub') }}"
